# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_zip_file', models.FileField(upload_to='code_zips/')),
                ('main_filename', models.CharField(max_length=255)),
                ('status', models.CharField(default='Open', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('video_file', models.FileField(upload_to=mp.models.project_segment_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.Project')),
            ],
        ),
    ]
