# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='section_count',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='section_unit',
            field=models.CharField(choices=[['sec', 'Seconds'], ['seg', 'Segments']], default='seg', max_length=10),
        ),
    ]
