# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import mp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_auto_20171031_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_zip_file',
        ),
        migrations.AddField(
            model_name='project',
            name='data_file',
            field=models.FileField(default=1, upload_to=mp.models.project_data_file_path),
            preserve_default=False,
        ),
    ]
