# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0006_segment_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
