# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0007_segment_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
