# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0008_auto_20171101_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
