# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp', '0009_auto_20171101_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='machine',
        ),
        migrations.AddField(
            model_name='segment',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
