# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0013_auto_20171101_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(default=None, null=True, upload_to='video_file/'),
        ),
    ]
